# https://docs.travis-ci.com/user/languages/php
language: php
sudo: required

# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty

services:
  - docker

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW_VERSION=1.32.0; PHPUNIT=5.7.*
      php: 7.1


# Dec 16, 2015 (GCE switch): Travis support wrote (Tomcat + Java):
# bug in the JDK: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7089443.
# The hostname for the precise-gce platform is longer than 64 characters on the
# VM your job is running on
#- sudo hostname "$(hostname | cut -c1-63)"
#- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
#- cat /etc/hosts # optionally check the content *after*

# Aug 12, 2016: (incident:2p40l49r3yxd) Travis support asks to add `sudo sysctl ...`
# After investigation, removed the lines from Dec 16, 2015 as it emptied the hosts file
before_install:
  - phpenv config-rm xdebug.ini # https://github.com/travis-ci/travis-ci/issues/1697
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - ip addr # for confirmation. can be skipped
  - cat /etc/hosts # optionally check the content *before*
  - docker pull mediawiki:$MW_VERSION
  - docker run -d -p 8080:80 -d
  - docker ps -a

cache:
  directories:
    - $HOME/.composer/cache
